project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - 00_*
    - 01_*
execute:
  freeze: auto
website:
  google-analytics: "G-LZ35J3XE4D"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "This project is in-development and in its current form should be taken seriously by no one"
    type: info
    position: below-navbar 
  page-navigation: true 
  title: "Statistics for Cytometry"
  navbar:
    logo: images/hex.svg
    background: white
    left:
      - text: "Home"
        href: index.qmd   
      - text: "Course"
        href: course/00_GatingSetSimple/index.qmd
    right:
    - icon: youtube
      href: https://www.youtube.com/@CytometryInR
      aria-label: YouTube
    - icon: github
      href: https://github.com/StepUpCytometry/StatisticsForCytometry
      aria-label: GitHub
  sidebar:
    style: floating
    collapse-level: 1
    contents:
    - section: "Is this thing on?"
      contents:
      - text: "00 - Gating Set - Simple"
        href: course/00_GatingSetSimple/index.qmd
      - text: "00 - Setting Up Stan"
        href: course/00_SettingUpStan/index.qmd
    - section: "Now We Are Cooking!"
      contents:
      - text: "01 - Getting Started"
        href: course/00_GettingStarted/index.qmd
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
   right: |
    ![AGPL-3.0](/images/AGPL3.png)
    ![CC-BY-SA](/images/CCBYSA.png)
format:
  html:
    css: styles.css

